- name: install all packages relevant to the web part of a lamp stack
  apt: name={{ item }} state=present
  with_items:
  - apache2 
  - php5
  - php5-mysql

- name: make sure apache2 is running
  service: name=apache2 state=started enabled=yes

